### ISSUE TITLE
Bypass mandrill for local installation?

### ISSUE THREAD

**Issue by ajhyndman** [curiositry/ReaDB#3]
Hey, this project seems pretty cool!

It's a shame that Meteor shut down their free hosting tier.  I was able to get the server running locally, but I don't have a Mandrill account.  Do you happen to know of a quick tweak I could make to bypass the Mandrill requirement?  Maybe I can hardcode a single account, for instance?

Thanks for your time.

**Comment by curiositry** [comment]
@ajhyndman Yes, you can. You can set a single account to active using Mongol (or some other tool) quite easily. Just sign up for an account, and at the step where you’re supposed to confirm your email address, open up the Mongol GUI (with control + M), set your newly-created account to “active”, and you’re done.

You could also change the Mail URL to use a different service, such as Postmark.

**Comment by curiositry** [comment]
(Speaking of which, now that Mandrill has shut down its free plans, I should change the default over to Postmark or Mailgun…)

**Comment by ajhyndman** [comment]
Thanks for the response!  I'll give it a shot.
